/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error': '#ffffff',
        'surface': '#faf9f5',
        'secondary-container': '#fdc5b6',
        'primary-container': '#bed9ee',
        'surface-container-highest': '#e3e2df',
        'surface-bright': '#faf9f5',
        'secondary-fixed-dim': '#f1baac',
        'on-secondary-container': '#794f44',
        'on-primary': '#ffffff',
        'secondary': '#7e5449',
        'surface-variant': '#e3e2df',
        'secondary-fixed': '#ffdbd1',
        'on-surface': '#1b1c1a',
        'on-secondary-fixed': '#30130b',
        'on-primary-container': '#465f71',
        'surface-container': '#efeeea',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#384b3a',
        'primary': '#486173',
        'inverse-surface': '#2f312e',
        'outline-variant': '#c2c7cc',
        'on-secondary-fixed-variant': '#633d33',
        'on-primary-fixed-variant': '#304a5b',
        'error': '#ba1a1a',
        'surface-tint': '#486173',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'surface-dim': '#dbdad6',
        'tertiary-fixed': '#d2e8d1',
        'inverse-primary': '#afcadf',
        'background': '#faf9f5',
        'surface-container-high': '#e9e8e4',
        'primary-fixed': '#cbe6fb',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#4d614f',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#0e1f11',
        'inverse-on-surface': '#f2f1ed',
        'on-background': '#1b1c1a',
        'tertiary-container': '#c5dbc4',
        'primary-fixed-dim': '#afcadf',
        'surface-container-low': '#f4f4f0',
        'outline': '#73787c',
        'on-surface-variant': '#42474c',
        'on-primary-fixed': '#011e2e',
        'tertiary': '#506351',
        'tertiary-fixed-dim': '#b7ccb6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '48px',
        'margin-mobile': '16px',
        gutter: '24px',
        'max-width': '1280px',
        base: '8px',
      },
      fontFamily: {
        quicksand: ['Quicksand', 'sans-serif'],
        nunito: ['Nunito', 'sans-serif'],
        fredoka: ['Fredoka', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
        'headline-lg-mobile': ['32px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-sm': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-md': ['28px', { lineHeight: '34px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
